CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE budget_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_name VARCHAR(255) NOT NULL,
    transaction_amount DECIMAL(10, 2),
    total_amount DECIMAL(10, 2),
    transaction_date DATE NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_receipt_user
                      FOREIGN KEY (user_id)
                      REFERENCES users(id)
);

CREATE TABLE budget_limit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    monthly_limit DECIMAL(10, 2) NOT NULL,
    period VARCHAR(7) NOT NULL,
    CONSTRAINT fk_budget_limit_user
                          FOREIGN KEY (user_id)
                          REFERENCES users(id),
    CONSTRAINT fk_budget_limit_category
                          FOREIGN KEY (category_id)
                          REFERENCES budget_category(id)
);

CREATE TABLE receipt_line_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(500),
    quantity INTEGER,
    price DECIMAL(10, 2),
    receipt_id BIGINT,
    category_id BIGINT,
    CONSTRAINT fk_line_item_receipt
                               FOREIGN KEY (receipt_id)
                               REFERENCES receipts(id),
    CONSTRAINT fk_line_item_category
                               FOREIGN KEY (category_id)
                               REFERENCES budget_category(id)
);