ALTER TABLE users
    ADD COLUMN password_changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE password_reset_tokens (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       user_id BIGINT NOT NULL,
                                       token_hash VARCHAR(64) NOT NULL UNIQUE,
                                       expires_at TIMESTAMP NOT NULL,
                                       used_at TIMESTAMP,
                                       created_at TIMESTAMP NOT NULL,
                                       CONSTRAINT fk_password_reset_token_user
                                           FOREIGN KEY (user_id)
                                               REFERENCES users(id)
);